nameSuffix: -dev
namespace: rag-app

commonLabels:
  app: rag-based-app
  environment: dev

resources:
  - secrets/nest-backend-secret.yaml
  - secrets/python-backend-secret.yaml

  - services/nest/nest-backend-deployment.yaml
  - services/nest/nest-backend-service.yaml

  - services/python/python-backend-deployment.yaml
  - services/python/python-backend-service.yaml
