apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
        - name: python-backend
          image: jithinksunil/rag_based_application:1
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: DATABASE_URL
            - name: NEST_BACKEND_BASE_URL
              value: 'http://nest-backend-service:8000/api'
            - name: REDIS_URL
              value: 'redis://redis-service:6379'
