apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: jithinksunil/rag_based_app_nest:latest
          ports:
            - containerPort: 8000
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: FRONTEND_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: DATABASE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: AWS_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: nest-backend-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: PORT
              value: '8000'
            - name: PYTHON_BACKEND_BASE_URL
              value: 'http://python-backend-service:8001/api'